name: Build and deploy Docker

on:
    push:
      branches:
        - main
      paths:
        - backend/DockerContainer/**
    workflow_dispatch:

jobs:
    build-and-push:
      runs-on: ubuntu-latest
      environment: production
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
        
        - name: Build Docker image
          run: docker build -t simple-node .
          working-directory: backend/DockerContainer
        
        - name: Docker login to Azure Container Registry
          run: docker login "${{ secrets.DOCKER_USERNAME }}.azurecr.io" -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Tag Docker image
          run: docker tag simple-node "${{ secrets.DOCKER_USERNAME }}.azurecr.io/simple-node:latest"

        - name: Push Docker image to ACR
          run: docker push "${{ secrets.DOCKER_USERNAME }}.azurecr.io/simple-node:latest"